
def handler(event, context):
    raise Exception("This is an error on purpose")
